### ISSUE TITLE
Can I use in app purchases with ExpoGo?

### ISSUE THREAD

**Issue by alexvazquez** [chroline/absurd-anecdotes#1]
Can I use in app purchases with ExpoGo?

**Comment by chroline** [comment]
> Can I use in app purchases with ExpoGo?


At this time, InAppPurchases is unavailable on Expo Go. Attempting to use the library with Expo Go will likely result in an error in your app. Instead, try wrapping your IAP code in a `try catch`block, and if you are running in Expo Go, send back mocked/simulated data instead of the real data that would be sent from the Expo Go library.

Hope that helps!
